[snippets]
versions = [
    "",
    "/v1",
    "/v2",
    "/v3",
    "/v4",
    "/v5",
    "/v6",
    "/v7",
    "/v8",
    "/v9",
    "/v10",
    "/beta",
    "/alpha",
    "/2023",
    "/2022",
    "/2021",
    "/2020",
    "/2019",
    "/legacy",
    "/new",
    "/latest",
    "/preview",
    "/dev",
    "/prod",
    "/test",
    "/staging",
    "/release",
]
resources = [
    "",
    "/api",
    "/users",
    "/products",
    "/orders",
    "/categories",
    "/tags",
    "/status",
    "/health",
    "/info",
    "/metrics",
    "/logs",
    "/config",
    "/settings",
    "/auth",
    "/login",
    "/logout",
    "/signup",
    "/password",
    "/emails",
    "/notifications",
    "/tasks",
    "/events",
    "/photos",
    "/videos",
    "/files",
    "/documents",
    "/articles",
    "/comments",
    "/feedback",
    "/support",
    "/updates",
    "/versions",
    "/history",
    "/analytics",
    "/reports",
    "/data",
    "/schemas",
    "/permissions",
    "/roles",
    "/groups",
    "/devices",
    "/networks",
    "/connections",
    "/ports",
    "/adapters",
    "/interfaces",
    "/protocols",
    "/services",
    "/applications",
    "/repositories",
    "/clients",
    "/servers",
    "/gateways",
    "/bridges",
    "/routers",
    "/switches",
    "/firewalls",
    "/batches",
    "/queues",
    "/streams",
    "/webhooks",
    "/alerts",
    "/transactions",
    "/wallets",
    "/payments",
    "/invoices",
    "/subscriptions",
    "/members",
    "/leases",
    "/reservations",
    "/bookings",
    "/tickets",
    "/dashboard",
    "/overview",
    "/summary",
    "/details",
    "/service",
    "/licenses",
    "/security",
    "/activate",
    "/verify",
    "/cancel",
]

[full]
known = [
    "/system/health",
    "/system/info/version",
    "/auth/login",
    "/auth/refresh_token",
    "/system/logs/errors",
    "/system/logs/access",
    "/metrics/system",
    "/metrics/application",
    "/config/reload",
    "/config/backup",
    "/status/service",
    "/health/full",
    "/info/licenses",
    "/logs/security",
    "/auth/token/validate",
    "/notifications/all",
    "/files/shared",
    "/documents/recent",
    "/articles/trending",
    "/feedback/general",
    "/support/faq",
    "/updates/features",
    "/versions/latest",
    "/analytics/usage",
    "/reports/financial",
    "/data/export",
    "/schemas/update",
    "/permissions/modify",
    "/roles/create",
    "/networks/config",
    "/protocols/overview",
    "/services/list",
    "/repositories/git",
    "/clients/web/config",
    "/servers/overview",
    "/gateways/traffic",
    "/switches/management",
]
